language: bash
script: 
  - asdf plugin test ant $TRAVIS_BUILD_DIR --asdf-plugin-gitref $TRAVIS_COMMIT ant -v
before_script:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install -y bsdmainutils; fi
  - git clone https://github.com/asdf-vm/asdf.git
  - . asdf/asdf.sh
matrix:
  include:
   - os: linux
     arch: amd64
   - os: linux
     arch: ppc64le
   - os: linux
     arch: arm64
   - os: osx
     arch: amd64